/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.triforcesoftware.frontend;

import com.mycompany.triforcesoftware.frontend.asistencia.AsistenciaPanel;
import com.mycompany.triforcesoftware.frontend.cargarArchivo.CargarArchivo;
import com.mycompany.triforcesoftware.frontend.evento.EventoPanel;
import com.mycompany.triforcesoftware.frontend.inscripcion.ParticipanteInscripcion;
import com.mycompany.triforcesoftware.frontend.pago.PagoPanel;
import com.mycompany.triforcesoftware.frontend.participante.ParticipantePanel;
import com.mycompany.triforcesoftware.frontend.registroActividad.RegistroActividadPanel;
import java.sql.SQLException;

/**
 *
 * @author huron_clinch
 */
public class TriforcePanel extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TriforcePanel.class.getName());

    /**
     * Creates new form Triforce
     */
    public TriforcePanel() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Triforce");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuResgistroParticipante = new javax.swing.JMenu();
        registroParticipante = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRegistroEvento = new javax.swing.JMenuItem();
        menuResgritoActividad = new javax.swing.JMenuItem();
        menuRegistroAsistencia = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuRegistroIncripcionEvento = new javax.swing.JMenu();
        menuInscripcionEvento = new javax.swing.JMenuItem();
        menuPago = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuCargarArchivo = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        menuResgistroParticipante.setText("Participamnte");

        registroParticipante.setText("Registrar Participante");
        registroParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroParticipanteActionPerformed(evt);
            }
        });
        menuResgistroParticipante.add(registroParticipante);

        jMenuBar1.add(menuResgistroParticipante);

        jMenu2.setText("Evento");

        menuRegistroEvento.setText("Registro evento");
        menuRegistroEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroEventoActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegistroEvento);

        menuResgritoActividad.setText("Registrar Actividad");
        menuResgritoActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuResgritoActividadActionPerformed(evt);
            }
        });
        jMenu2.add(menuResgritoActividad);

        menuRegistroAsistencia.setText("Registrar Asistencia");
        menuRegistroAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroAsistenciaActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegistroAsistencia);

        jMenuItem7.setText("Certificado");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        MenuRegistroIncripcionEvento.setText("Inscripcion");

        menuInscripcionEvento.setText("Inscripcion a evento");
        menuInscripcionEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInscripcionEventoActionPerformed(evt);
            }
        });
        MenuRegistroIncripcionEvento.add(menuInscripcionEvento);

        menuPago.setText("Pago");
        menuPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagoActionPerformed(evt);
            }
        });
        MenuRegistroIncripcionEvento.add(menuPago);

        jMenuBar1.add(MenuRegistroIncripcionEvento);

        jMenu7.setText("Reportes");
        jMenuBar1.add(jMenu7);

        jMenu1.setText("Cargar archivo");

        menuCargarArchivo.setText("Cargar");
        menuCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCargarArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(menuCargarArchivo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistroEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroEventoActionPerformed
        repintarJDesktop();
        EventoPanel panel = new EventoPanel();
        jDesktopPane1.add(panel).setVisible(true);
    }//GEN-LAST:event_menuRegistroEventoActionPerformed

    private void registroParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroParticipanteActionPerformed
        repintarJDesktop();
        ParticipantePanel panel = new ParticipantePanel();
        jDesktopPane1.add(panel).setVisible(true);
    }//GEN-LAST:event_registroParticipanteActionPerformed

    private void menuInscripcionEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInscripcionEventoActionPerformed
        repintarJDesktop();
        try {
            ParticipanteInscripcion panel = new ParticipanteInscripcion();
            jDesktopPane1.add(panel).setVisible(true);
        } catch (SQLException e) {
            System.out.println("Error al ingresar a menu inscripcion");
            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_menuInscripcionEventoActionPerformed

    private void menuPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagoActionPerformed
        repintarJDesktop();
        try {
            PagoPanel panel = new PagoPanel();
            jDesktopPane1.add(panel).setVisible(true);
        } catch (SQLException e) {
            System.out.println("Error al ingresar a menu pago");
            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_menuPagoActionPerformed

    private void menuCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargarArchivoActionPerformed
        repintarJDesktop();
        CargarArchivo panel = new CargarArchivo();
        jDesktopPane1.add(panel).setVisible(true);
    }//GEN-LAST:event_menuCargarArchivoActionPerformed

    private void menuResgritoActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuResgritoActividadActionPerformed
        repintarJDesktop();
        RegistroActividadPanel panel = new RegistroActividadPanel();
        jDesktopPane1.add(panel).setVisible(true);
    }//GEN-LAST:event_menuResgritoActividadActionPerformed

    private void menuRegistroAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroAsistenciaActionPerformed
        repintarJDesktop();
        AsistenciaPanel panel = new AsistenciaPanel();
        jDesktopPane1.add(panel).setVisible(true);
    }//GEN-LAST:event_menuRegistroAsistenciaActionPerformed

    private void repintarJDesktop() {
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuRegistroIncripcionEvento;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem menuCargarArchivo;
    private javax.swing.JMenuItem menuInscripcionEvento;
    private javax.swing.JMenuItem menuPago;
    private javax.swing.JMenuItem menuRegistroAsistencia;
    private javax.swing.JMenuItem menuRegistroEvento;
    private javax.swing.JMenu menuResgistroParticipante;
    private javax.swing.JMenuItem menuResgritoActividad;
    private javax.swing.JMenuItem registroParticipante;
    // End of variables declaration//GEN-END:variables
}
